### PR TITLE
Fix stray SVGGraphics cast

### LINKED ISSUE #695: Can't save png or jpeg images with IGV 2.7.0-rc1
I'm running the Mac App.

File > Save Image doesn't work for jpeg and png files. No file is created.
svg files are created ok.

The following errors are produced in the log:

PNG:

ERROR [2019-09-23T18:40:09,400] [DefaultExceptionHandler.java:49]  Unhandled exception
java.lang.ClassCastException: class sun.java2d.SunGraphics2D cannot be cast to class org.apache.batik.svggen.SVGGraphics2D (sun.java2d.SunGraphics2D is in module java.desktop of loader 'bootstrap'; org.apache.batik.svggen.SVGGraphics2D is in module batik.svggen@1.11 of loader 'app')
        at org.broad.igv.ui.util.SnapshotUtilities.exportScreenShotBufferedImage(SnapshotUtilities.java:298) ~[igv.jar:?]
        at org.broad.igv.ui.util.SnapshotUtilities.doComponentSnapshot(SnapshotUtilities.java:144) ~[igv.jar:?]
        at org.broad.igv.ui.IGV.createSnapshotNonInteractive(IGV.java:766) ~[igv.jar:?]
        at org.broad.igv.ui.IGV.createSnapshot(IGV.java:710) ~[igv.jar:?]
        at org.broad.igv.ui.IGV.saveImage(IGV.java:692) ~[igv.jar:?]
        at org.broad.igv.ui.IGV.saveImage(IGV.java:686) ~[igv.jar:?]
        at org.broad.igv.ui.IGVMenuBar$3.actionPerformed(IGVMenuBar.java:333) ~[igv.jar:?]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[?:?]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[?:?]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[?:?]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[?:?]
        at javax.swing.AbstractButton.doClick(Unknown Source) ~[?:?]
        at com.apple.laf.ScreenMenuItem.actionPerformed(Unknown Source) ~[?:?]
        at java.awt.MenuItem.processActionEvent(Unknown Source) ~[?:?]
        at java.awt.MenuItem.processEvent(Unknown Source) ~[?:?]
        at java.awt.MenuComponent.dispatchEventImpl(Unknown Source) ~[?:?]
        at java.awt.MenuComponent.dispatchEvent(Unknown Source) ~[?:?]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
        at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
        at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
        at java.awt.EventQueue$5.run(Unknown Source) ~[?:?]
        at java.awt.EventQueue$5.run(Unknown Source) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:?]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
        at java.awt.EventDispatchThread.run(Unknown Source) [?:?]

JPEG:

ERROR [2019-09-23T18:43:00,140] [DefaultExceptionHandler.java:49]  Unhandled exception
java.lang.ClassCastException: class sun.java2d.SunGraphics2D cannot be cast to class org.apache.batik.svggen.SVGGraphics2D (sun.java2d.SunGraphics2D is in module java.desktop of loader 'bootstrap'; org.apache.batik.svggen.SVGGraphics2D is in module batik.svggen@1.11 of loader 'app')
        at org.broad.igv.ui.util.SnapshotUtilities.exportScreenShotBufferedImage(SnapshotUtilities.java:298) ~[igv.jar:?]
        at org.broad.igv.ui.util.SnapshotUtilities.doComponentSnapshot(SnapshotUtilities.java:144) ~[igv.jar:?]
        at org.broad.igv.ui.IGV.createSnapshotNonInteractive(IGV.java:766) ~[igv.jar:?]
        at org.broad.igv.ui.IGV.createSnapshot(IGV.java:710) ~[igv.jar:?]
        at org.broad.igv.ui.IGV.saveImage(IGV.java:692) ~[igv.jar:?]
        at org.broad.igv.ui.IGV.saveImage(IGV.java:686) ~[igv.jar:?]
        at org.broad.igv.ui.IGVMenuBar$3.actionPerformed(IGVMenuBar.java:333) ~[igv.jar:?]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[?:?]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[?:?]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[?:?]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[?:?]
        at javax.swing.AbstractButton.doClick(Unknown Source) ~[?:?]
        at com.apple.laf.ScreenMenuItem.actionPerformed(Unknown Source) ~[?:?]
        at java.awt.MenuItem.processActionEvent(Unknown Source) ~[?:?]
        at java.awt.MenuItem.processEvent(Unknown Source) ~[?:?]
        at java.awt.MenuComponent.dispatchEventImpl(Unknown Source) ~[?:?]
        at java.awt.MenuComponent.dispatchEvent(Unknown Source) ~[?:?]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
        at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
        at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
        at java.awt.EventQueue$5.run(Unknown Source) ~[?:?]
        at java.awt.EventQueue$5.run(Unknown Source) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:?]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:?]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
        at java.awt.EventDispatchThread.run(Unknown Source) [?:?]

### PR DESCRIPTION
**Pull request by brainstorm**
Fixes #695

### CODE REVIEW

**Comment by brainstorm** [comment]
Both formats working now...

igv_snapshot
igv_snapshot

**Comment by brainstorm** [comment]
SVG too, of course.

**Comment by jrobinso** [comment]
Cool you beat me to this!  I suspected the cast.   Thanks a lot.

**Comment by brainstorm** [comment]
No worries Jim, eager to see this finally shipped as 2.7.0 proper ;)

**Pull request merged**
