### PR TITLE
Update AlignmentTrack.java

### PR DESCRIPTION
**Pull request by CJ-Chen**
"insertionRect" needs to be initialized though not displayed.
It might cause a null pointer exception in Line 709 "Rectangle iRect = new Rectangle(inputRect.x, insertionRect.y, inputRect.width, insertionRect.height);"
when some alignment tracks are displaying insertion markers while others do not.

### CODE REVIEW

**Comment by CJ-Chen** [comment]
Sorry for this PR.
It seems that this modification will consume much more time for graph rendering. 
I don't know why.

**Comment by CJ-Chen** [comment]
Maybe we can use "insertionRect.setBounds(rect);" to replace "insertionRect = new Rectangle(rect);" around line 523?

**Comment by jrobinso** [comment]
I'll investigate when I can find time, but do you have steps to reproduce an issue?  In what situation did an error occur?

**Comment by CJ-Chen** [comment]
> I'll investigate when I can find time, but do you have steps to reproduce an issue? In what situation did an error occur?

Here is a genome with two alignment track. One is displaying with “Show Insertion Mark” and the other without selected this option.



And when i click this the insertion mark. It will report a null pointer exception that mention above.



```
igv.log:
SEVERE [10月 27,2022 14:00] [DataPanel] Error painting DataPanel
SEVERE [10月 27,2022 14:00] [DataPanel] java.lang.NullPointerException
	at org.igv/org.broad.igv.sam.AlignmentTrack.renderExpandedInsertion(AlignmentTrack.java:679)
	at org.igv/org.broad.igv.ui.panel.DataPanelPainter.paintExpandedInsertion(DataPanelPainter.java:214)
	at org.igv/org.broad.igv.ui.panel.DataPanelPainter.paint(DataPanelPainter.java:89)
	at org.igv/org.broad.igv.ui.panel.DataPanel.paintComponent(DataPanel.java:154)
```

Sorry for the inconvenience.

**Comment by jrobinso** [comment]
What version of IGV are you using?  I can't reproduce this error, and the line numbers in the igv.log stack trace do not match the current code.

**Comment by jrobinso** [comment]
I can't reproduce the error just loading tracks, only after loading tracks via a session.  So I think this is the same error as reported here: https://github.com/igvteam/igv/issues/1252.   I will close this PR as a duplicate bug report.

**Pull request closed without merging**
