### PR TITLE
Replace all instances of Feature.getChr with getContig

### PR DESCRIPTION
**Pull request by lbergelson**
@jrobinso It sounds like this is causing problems so I've updated all the deprecated calls to getChr.

* Replacing all instances of `Feature.getChr()` with the equivalent `Feature.getContig()`.
* Fixing some place where `getChr` and `getContig` were implemented differently.
  If they differed I resolved the differences by using the `getChr` implementation.
* Removing redundant implementations of `getChr` and allowing the default
implementation to be used.

### CODE REVIEW

**Comment by jrobinso** [comment]
Thanks but I'm not going to make this change, too ugly.

**Comment by lbergelson** [comment]
It's fine if you don't want it, but it's a binary compatible change that should be completely transparent to downstream users of IGV as a library.  It also fixed a few bugs where getContig and getChr were defined to return different results.  It might be worth incorporating those.

**Comment by lbergelson** [comment]
Actually, I'm not 100% certain that it's binary compatible, but it's definitely source compatible...  I'm not certain if replacing an overload with a default method is binary compatible...

**Comment by jrobinso** [comment]
Thanks for the effort, I appreciate it,  I just don't want "getContig" everywhere.    There are 125 files changed here,  I'll see if I can find the bugs you allude to.

**Pull request closed without merging**
