### PR TITLE
Add option to color bases by SMRT kinetic values

### PR DESCRIPTION
**Pull request by ctsa**
I created a branch that allows us to view SMRT sequencing polymerase kinetics stored in the BAM file. The kinetics values of interest are the pulse width (PW) and interpulse duration (IPD). The changes allow viewing of these kinetic values from both subread and CCS SMRT sequencing BAM files that include kinetics tags.

As an example, below is a view of E coli CCS sequence, where bases have been colored to indicated the interpulse duration (IPD) on the fwd-aligned strand. The red column corresponds to a 6mA methylation site at the _Dam_ methyltransferase recognition site (GATC).

image

The new feature is added to the "Color alignments by" context menu. The menu has been modified with the following 6 options:

image

While this is a somewhat specialized feature, I wanted to open a discussion on whether we might bring this into the master branch, or what further changes would make this possible.

### CODE REVIEW

**Comment by jrobinso** [comment]
Awesome!  I assume this is of interest primarily to developers of base modification callers, not the general pacbio end user.   One thought -- should we include "ZMW" and "movie" in this grouping?   

I would tentatively suggest making this a submenu, but I am currently considering flattening the existing bisulfite mode submenu to save clicks.   But that is an orthogonal UI issue.

@amwenger any comments here?

**Comment by jrobinso** [comment]
BTW if you guys have any data with modifications other than 5mC / 5hmC you can share it would be great for my development/test collection.

**Comment by ctsa** [comment]
@jrobinso that is correct, it is of interest for a specialized development case, so I'm interested in finding the balance between what you'll want to manage the UX for typical users vs. the code sync problems that will come up if we try to keep this in an unmerged branch.

Also may benefit from feedback by @mrvollger and @VRam142

**Comment by ctsa** [comment]
In addition to considering options like submenus, this might also be something that could appear when a `developer` flag is toggled in preferences?

I'm not sure we would want to group it with items like ZMW and movie, which should be of more general interest.

**Comment by mrvollger** [comment]
This is a great feature, Thanks Chris! My vote would be to just have a submenu but any way to do this would be great.

**Comment by jrobinso** [comment]
OK, give me a little time to consider the best way to integrate this.

**Comment by jrobinso** [comment]
Also,  can someone provide me with some test data, along with a screenshot of what it should look like?   Just extracting the region corresponding to the screenshot above would suffice.

**Comment by amwenger** [comment]
> I would tentatively suggest making this a submenu

I agree that including this feature in a submenu is a good idea so that it is accessible for developers but does not expand the list too much.  Perhaps a "SMRT kinetics" submenu where "SMRT" is then dropped from the options: i.e. "subread IPD" instead of "SMRT subread IPD".

> One thought -- should we include "ZMW" and "movie" in this grouping?

I like keeping ZMW and movie at the top-level.  But - if the lists become too long - it could make sense to add a "PacBio" or "PacBio-specific" submenu with ZMW, movie, and the SMRT kinetics options.

Coloring and grouping by ZMW is most useful for subreads, and so - with the adoption of HiFi reads - is now more of a developer feature.  Grouping by movie is still fairly general interest.

> BTW if you guys have any data with modifications other than 5mC / 5hmC you can share it would be great for my development/test collection.

We will share other calls once we have them.

**Comment by ctsa** [comment]
@jrobinso - I'll get you a bamlet of the example region in E coli, hopefully later today.

@amwenger - The "SMRT kinetics" submenu sounds like a nice way to organize this.

**Comment by ctsa** [comment]
@jrobinso  - I've attached a test bamlet to a test release I made of an earlier IGV build here:

https://github.com/ctsa/igv/releases/tag/ipd_color_1

The bamlet is a view of the position range 22448-22451 from E coli K12 covering the _Dam_ recognition site from the above example. In the example view I'm showing "CCS fwd-strand aligned IPD".

**Comment by ctsa** [comment]
Hi @jrobinso - We're starting to get more folks trying this feature out, so I fixed a few reported issues today. There are 4 new fix commits on top of the original pull request.

If it doesn't interfere with anything you've looked into so far, I could go ahead and (1) rebase this branch with the latest master and (2) implement Aaron's suggestion of a "SMRT kinetics" submenu. What do you think?

Also I will be uploading a bam for subread kinetics testing soon, to complement the above example CCS kinetics bamlet.

**Comment by jrobinso** [comment]
Yes go ahead and rebase.  I probably won't be able to look at this until the end of next week.    I like the idea of a development flag to enable the menu,  so in that case a sub menu is not so important as its only going to be visible to those who really want it.

**Comment by ctsa** [comment]
Thanks, I'll go ahead with the rebase and look into the flag impl.

I also went ahead and put together a small example for viewing subread kinetics with a bam file of subreads for a single zmw aligned to the ccs sequence as reference. Uploaded to a github release here:

https://github.com/ctsa/igv/releases/tag/ipd_color_4

**Comment by ctsa** [comment]
Hi @jrobinso - Sorry it took a bit for me to look into it, but it turned out to be relatively simple to put this feature behind a checkbox in preferences. After rebasing the branch to latest master, I added a new commit  showing a proposed implementation. This update would add an option to the 'Third Gen' preferences tab as follows:

image

**Comment by ctsa** [comment]
Thanks, yes I confirm this isn't holding anything up on our end and I'm not planning any more work unless bugfix requests come up.

**Comment by ctsa** [comment]
Hi @jrobinso - Anything I can do to help refactor this?

**Comment by jrobinso** [comment]
@ctsa I don't think so, but the main goals of refactoring this PR would be to reduce or eliminate the bulk of changes to generic classes and interfaces like Alignment, AlignmentRenderer, and SAMAlignment for this very specialized and technical use case.    Its not obvious how to do that or I would have done it.    I am aware of this, but have not had time to focus on it yet.

**Comment by jrobinso** [comment]
OK I'm going to try to tackle this by the end of the year.  Being realistic here.    As noted earlier I don't want to make changes to the generic Alignment interface for such a technology specific, and for most arcane use case,  that is the main challenge.  However it should be solvable.

I don't know the subject matter here, and have only a vague idea of what we are talking about.   The example here will be invaluable, but I will need some instructions.    What options should I try, and what should they look like?   Instructions with screenshots would be useful.   https://github.com/ctsa/igv/releases/tag/ipd_color_4

**Comment by ctsa** [comment]
Thanks @jrobinso ,

For the subreads example data included here:

https://github.com/ctsa/igv/releases/tag/ipd_color_4

...after loading the fasta and bam file, go to locus: "m64002_220618_180054/118425111/ccs:1-200".


Selecting "Color alignments by" -> "SMRT subread IPD" should show the following view:

image


Selecting "Color alignments by" -> "SMRT subread PW" should show the following view:

image

I will make a separate comment below for the CCS example.

**Comment by ctsa** [comment]
For ccs example data, you can use the bam here:

https://github.com/ctsa/igv/releases/tag/ipd_color_1

Select "Ecoli K12..." as the reference and load the bam file. Go to locus "gi|49175990|ref|NC_000913.2|:22,408-22,492".


Selecting "Color alignments by" -> "SMRT CCS fwd-strand aligned IPD" should show the following view:
 
image


Selecting "Color alignments by" -> "SMRT CCS fwd-strand aligned PW" should show the following view:
 
image


Selecting "Color alignments by" -> "SMRT CCS rev-strand aligned IPD" should show the following view:

image


Selecting "Color alignments by" -> "SMRT CCS rev-strand aligned PW" should show the following view:

image

**Comment by jrobinso** [comment]
@ctsa I've hand merged this and done some refactoring.  The merging was a bit of a nightmare, not your fault, too many changes while this PR languished.   Anyway I'm pretty sure i got it all,  there is a new PR with the merged branch   here 
 #1270.   If you want to pull and test that, or just examine the code, feel free but I have done all the tests outlined above.   I will merge this probably Friday if I don't hear otherwise.

**Comment by ctsa** [comment]
Thanks Jim! I'll make a test build from the new branch now and let you know if anything comes up.

**Comment by ctsa** [comment]
I checked the behavior and the new code diff to master, it all looks ship-shape. Thanks again for getting this refactored for merge.

**Comment by jrobinso** [comment]
@ctsa Great.  Could you provide a short snippet for each menu item, just defining the terms (e.g. I assume IPD is inter-pulse distance) and what the color or color intensity means?   If you can do that I will add it to the documentation somewhere.

**Comment by ctsa** [comment]
Hi Jim, Here is a first pass at some material to document this feature (I will follow with another comment containing a color scale figure):

# SMRT kinetics color key

All SMRT kinetics coloration options adjust the color to scale with the frame count. From 0 to 100 frames the color is set to red and the alpha channel is adjusted from 0 to 255 (from transparent to opaque). From 100 to 600 frames, the color is adjusted from red to yellow. From 600 to 6000 frames the color is adjusted from yellow to cyan.

# SMRT kinetics color options

## SMRT subread IPD

For subread or CLR sequences, color bases according to the IPD value found in the BAM record’s ‘ip’ tag. No color is applied to reads where this tag is not found.

## SMRT subread PW

For subread or CLR sequences, color bases according to the PW value found in the BAM record’s ‘pw’ tag. No color is applied to reads where this tag is not found.

## SMRT CCS fwd-strand aligned IPD

For CCS sequences, color bases according to the IPD value of the CCS strand aligned in the forward orientation. This will display values from the BAM record’s ‘fi’ tag or ‘ri’ tag, for reads aligned in the forward or reverse orientation, respectively. No color is applied to reads where the expected tag is not found.

## SMRT CCS fwd-strand aligned PW

For CCS sequences, color bases according to the PW value of the CCS strand aligned in the forward orientation. This will display values from the BAM record’s ‘fp’ tag or ‘rp’ tag, for reads aligned in the forward or reverse orientation, respectively. No color is applied to reads where the expected tag is not found.

## SMRT CCS rev-strand aligned IPD

For CCS sequences, color bases according to the IPD value of the CCS strand aligned in the reverse orientation. This will display values from the BAM record’s ‘ri’ tag or ‘fi’ tag, for reads aligned in the forward or reverse orientation, respectively. No color is applied to reads where the expected tag is not found.

## SMRT CCS rev-strand aligned PW

For CCS sequences, color bases according to the PW value of the CCS strand aligned in the reverse orientation. This will display values from the BAM record’s ‘rp’ tag or ‘fp’ tag, for reads aligned in the forward or reverse orientation, respectively. No color is applied to reads where the expected tag is not found.

# References

## SMRT kinetics terms

- SMRT – single molecule real-time sequencing
- CCS – circular consensus sequencing
- IPD – interpulse duration – the number of camera frames between pulse signals
- PW – pulse width – the number of camera frames comprising a pulse signal

## Bam format documentation

Description of SMRT kinetics tags in subread BAM files:

https://pacbiofileformats.readthedocs.io/en/11.0/BAM.html#use-of-read-tags-for-per-read-base-information

Description of SMRT kinetics tags in CCS BAM files:

https://pacbiofileformats.readthedocs.io/en/11.0/BAM.html#use-of-read-tags-for-hifi-per-read-base-kinetic-information

**Comment by ctsa** [comment]
Color scale image:

image

I have a powerpoint file used to draw this image, if you would find this helpful I can attach it to one of the branch releases.

**Comment by jrobinso** [comment]
OK #1270 is merged, thanks for contribution!  And also the documentation,  I don't think I'll need the powerpoint.

This will be included in the next release,  no ETA on that yet but we usually don't go more than a month between releases.  Probably early in January.

**Comment by jrobinso** [comment]
@ctsa this is now released in 2.16.0

**Comment by ctsa** [comment]
Awesome -- Thanks Jim!

**Pull request closed without merging**
