### PR TITLE
Linking project overview dashboard to README

### PR DESCRIPTION
**Pull request by alexkarezin**
Adding a link to the README header. Dashboard describes overall project structure and dependencies. Will be useful for new developers looking to contribute to the project. Direct link: https://sourcespy.com/github/igvteamigv/

### CODE REVIEW

**Comment by alexkarezin** [comment]
I think this overview will be useful for new contributors, any chance Jim (@jrobinso) can look at this? Thank you!

**Comment by jrobinso** [comment]
Its an interesting tool, but adds more confusion than clarity I think.

**Comment by alexkarezin** [comment]
@jrobinso Jim, thank you for the feedback. Any chance you can, clarify which particular part was confusing and maybe how the same task could be achieved better. Really appreciate it. Thank you and I wont be pestering you again!

**Comment by jrobinso** [comment]
@alexkarezin Actually has anything changed?  The first time I looked I thought it had picked up Enterprise and Web components, neither of which we have.   It looks better now, or my memory is bad.

Could you tell me something about sourcespy.com?   Do you plan to have ads on the linked page?

**Comment by alexkarezin** [comment]
@jrobinso 
Jim, The picture is continuously updating to become more relevant.
The service will never advertise or require payments - it is an honest attempt to help new contributors learn product architecture and technologies involved. Does not require maintenance as the whole description is generated from repository. Hope this helps.

**Comment by jrobinso** [comment]
Merged,  I find it helpful for my own use, especially the Swing diagram.

**Pull request merged**
