### PR TITLE
command -  sort by attribute

### PR DESCRIPTION
**Pull request by joshua-gould**

### CODE REVIEW

**Comment by jrobinso** [comment]
@joshua-gould This will break if an attribute name just happens to equal an alignment sort option.  I think I would prefer an explicit command, since "sort" is taken. maybe "sortTracks" or "sortByAttribute".     This same critique could be applied to the seg copy # test, "region score", but in that case we have complete control of the vocabulary.

**Comment by joshua-gould** [comment]
How about this syntax:
sortTracks trackName (asc|desc), trackName (asc,desc), etc...

**Comment by jrobinso** [comment]
I don't understand that syntax,  what is trackName?  Sorting by attricture sorts tracks,  it doesn't make sense for an individual track.  Also,  what happened to the attribute argument?

Since this PR is to implement "sortByAttribute",   lets just call it "sortByAttribute".   That sorts all tracks, its what sorting by attribute does.   I assume the list defines secondary, tertiary, etc sorts.   So

sortByAttribute attribute1 (asc|desc),  attribute2 (asc|desc), ...

**Comment by joshua-gould** [comment]
Yes, sorry I mean attribute instead of trackName. Should asc|desc be optional or mandatory?

**Comment by joshua-gould** [comment]
I updated the command. Syntax is sortByAttribute attributeName asc|desc ....
Example: Sort by attribute1 descending: sortByAttribute attribute1 desc
Example: Sort by attribute1 ascending, then by attribute2 descending: sortByAttribute attribute1 asc attribute2 desc

**Comment by jrobinso** [comment]
OK,  I'll look at this as soon as I can.

**Pull request closed without merging**
