### PR TITLE
Load tracks from s3 URL after accessibility check #1101

### PR DESCRIPTION
**Pull request by qing-at-work**
Load tracks from s3 URL after accessibility check #1101

### CODE REVIEW

**Comment by jrobinso** [comment]
@qing-at-work Yes that is quite obviously a bug.  I suppose the Cognito users we have, which are mostly at UMCCR, were using the S3 "picker" to load files.

Looking at this, I think the s3 AWS check shoule be just before line 94, its possible someone stores a session file in S3.   Could you try placing it there, and if successful modify the PR?  This is what I think should be done.  

```
                   final String url = mapURL(inputURL.trim());

                    if (url.startsWith("s3://")) {
                        checkAWSAccessbility(url);
                    }
                    if (SessionReader.isSessionFile(url)) {
                        try {
                            LongRunningTask.submit(() -> this.igv.loadSession(url, null));
                        } catch (Exception ex) {
                            MessageUtils.showMessage("Error loading url: " + url + " (" + ex.toString() + ")");
                        }
                    } else {
                        ResourceLocator rl = new ResourceLocator(url.trim());

                        if (dlg.getIndexURL() != null) {
                            String indexUrl = dlg.getIndexURL().trim();

                            if (GoogleUtils.isGoogleCloud(indexUrl) || GoogleUtils.isGoogleDrive(indexUrl)) {
                                enableGoogleMenu();
                            }

                            rl.setIndexPath(indexUrl);
                        }
                        igv.loadTracks(Arrays.asList(rl));

                    }
```

**Comment by jrobinso** [comment]
@qing-at-work Looks good, but could you confirm that you tested this in your environment?

**Comment by qing-at-work** [comment]
> @qing-at-work Looks good, but could you confirm that you tested this in your environment?

Yes @jrobinso, I have tested this fix in my local environment (Windows Server 2019).

**Comment by jrobinso** [comment]
OK thanks for the fix.

**Pull request merged**
